### PR TITLE
Add/gas fee estimator docs

### PR DESCRIPTION
**Pull request by harsenyan3**
#286

### CODE REVIEW

**Review by smk762 — COMMENTED** [review]
Using the latest release, I am unable to get a response from these methods. 
- `get_eth_estimated_fee_per_gas` -> `Gas fee estimation not supported for this coin`
- `start_gas_fee_estimator` -> `NoSuchMethod`
- `stop_gas_fee_estimator` -> `NoSuchMethod`

cc: @dimxy

**Comment by dimxy** [comment]
> * start_gas_fee_estimator

Sorry, I renamed those rpcs to
```
start_eth_fee_estimator
stop_eth_fee_estimator
```
(btw I have a bug when the eth fee estimator does not start if the new 'enable_eth_with_tokens' rpc was used to enable coins, it starts okay only if the old 'enable' rpc used. Fixed in my current work for access lists #2170)

**Comment by smk762** [comment]
Set to "draft" until https://github.com/KomodoPlatform/komodo-defi-framework/pull/2170#issuecomment-2348290873 is resolved

**Comment by dimxy** [comment]
Plz be aware that gas fee estimator rpcs 
```
start_eth_fee_estimator
stop_eth_fee_estimator
```
will be removed in this PR [2172](https://github.com/KomodoPlatform/komodo-defi-framework/pull/2172) as it will be managed by the new streaming API rpc "fee_estimator::enable"

**Comment by smk762** [comment]
Closing in favor of https://github.com/KomodoPlatform/komodo-docs-mdx/pull/293

**Pull request closed without merging**
