### PR TITLE
added title and description to all pages

### PR DESCRIPTION
**Pull request by gaeacodes**

### CODE REVIEW

**Comment by gcharang** [comment]
@smk762 I asked @gaeacodes to use chatgpt to generate titles and descriptions for each of the docs for SEO. please review at your convenience

**Comment by smk762** [comment]
I'm getting a build error with this.
image
Seems the build is seeing the submodule declaration as well as the same content generated by `update-content.sh`
image

**Comment by smk762** [comment]
Its probably better to use SEO optimised titles. Does this also affect anchor hyperlinks?
Some of the generated titles include special chars like `:` or `,`. How are these handled?
@gcharang I assume the generated titles were intended for the html `<title>` tag values? 
In this case, we could use a different variable name like `seo_title` and use that by default, but if it is `undefined`, use the first `h1` value as title too. 
Inversely, where a `h1` does not exist, but `title` does, injecting a hidden `h1` with same value would be better for SEO than not having a `h1`

**Comment by gcharang** [comment]
@smk762 yes, the extra title/description we have exported in this PR is for the <title> tag, ` <meta name="description"` tag.
and for fb/twitter specific tags like:
```
<meta property="og:title" content={finTitle} />
<meta property="og:description" content={finDesc} />
<meta name="twitter:title" content={finTitle} />
<meta name="twitter:description" content={finDesc} />
```
> Does this also affect anchor hyperlinks?

can you explain more? do you mean the preview text and image that are displayed when we paste a URL on discord/twitter/other social sites?

> Some of the generated titles include special chars like : or ,. How are these handled?

ksnip_20230525-194726

Titles can have special characters though


> Inversely, where a h1 does not exist, but title does, injecting a hidden h1 with same value would be better for SEO than not having a h1

we have to add a h1 for each page and make the build fail if one doesn't exist. there shouldn't be a situation where we/someone took the time to write a SEO-optimized title tag, but failed to write the actual h1 ?

@Emmaccen please make it so that h1 is used for the <title> tag if explicit `export title` doesn't exist. and use the exported value always if it is available

**Comment by smk762** [comment]
> can you explain more? do you mean the preview text and image that are displayed when we paste a URL on discord/twitter/other social sites?

I mean how the anchor links are generated. I noticed or example, with the standard objects something called `SomethingSomething` would get an anchor tag of `#something-something`, and there are other examples also. I assume if title tags contain special chars, they will be stripped out if used for any anchor links (eg if title value becomes a h1)

**Comment by gcharang** [comment]
@smk762 
>  they will be stripped out if used for any anchor links (eg if title value becomes a h1)

got it, that's why it isn't a good idea to use the SEO optimized title tags for h1s. we should write h1s manually. and if a h1 did have those characters, they will be stripped out when turning it into a id/hash cc: @Emmaccen

**Comment by gaeacodes** [comment]
please hold off on reviewing this PR. I'm editing some of the files to improve currently committed titles and descriptions. I will mark as `Ready for review` when ready

**Comment by gaeacodes** [comment]
hey @smk762 @gcharang I have updated many titles and descriptions for clarity and correctness. Also, added them for the new lightning docs. Please review.

**Comment by smk762** [comment]
> hey @smk762 @gcharang I have updated many titles and descriptions for clarity and correctness. Also, added them for the new lightning docs. Please review.

Apologies for delay, will check them today

**Comment by smk762** [comment]
Looks good in the most part for pages I browsed thru until I encountered this
image

@gcharang is there a simple sitemap that can be generated / output? this might be useful for automated testing of all urls. Assuming the sidebar.ts file contains it all (please confirm), should be easy to enough to parse it into a valid json file via a small script in the utils folder.

**Comment by gcharang** [comment]
@smk762 
>  is there a simple sitemap that can be generated / output? this might be useful for automated testing of all urls. Assuming the sidebar.ts file contains it all (please confirm), should be easy to enough to parse it into a valid json file via a small script in the utils folder.

gaeacodes is working on creating the sitemap. created an issue on the build repo to track it. current sidebar.ts is not perfect. has some additional entries and some missing docs. so, creating sitemap from the file/folder structure itself

**Comment by gaeacodes** [comment]
@smk762 @gcharang built the docs site using updated content from this PR and fixed errors like the missing h1's and content like `<rel>` being considered jsx. Now, all the pages should build successfully.

**Review by gcharang — APPROVED** [review]

**Review by smk762 — APPROVED** [review]
Thanks - all pages navigated to and no errors returned.

**Pull request merged**
